# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 08:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_messages', models.IntegerField(default=0)),
                ('num_of_users', models.IntegerField(default=0)),
                ('lastMessageId', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(default=None, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(auto_now=True, verbose_name='creation time'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mess.MessageThread'),
        ),
    ]
