# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_auto_20160829_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagethread',
            old_name='lastMessageId',
            new_name='last_message_id',
        ),
    ]
