# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='thread',
        ),
    ]
