# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_bug',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_report',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='reviewers',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='watchers',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creation_time',
            field=models.DateTimeField(default=None, verbose_name='creation time'),
        ),
    ]
