# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_auto_20160329_0746'),
        ('bugs', '0002_auto_20160425_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creator',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_bug',
            field=models.BooleanField(default=True, verbose_name='is_bug'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_report',
            field=models.BooleanField(default=False, verbose_name='is_report'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reviewers',
            field=models.ManyToManyField(default=None, related_name='reviewers_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(default=None, related_name='watchers_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
