# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 06:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_auto_20160426_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_bug',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_report',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Баг', 'Баг'), ('Отчет', 'Отчет')], default='Баг', max_length=5),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creation_time',
            field=models.DateTimeField(auto_now=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reviewers',
            field=models.ManyToManyField(default=None, null=True, related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(default=None, null=True, related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
