# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_auto_20160329_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online_chat_users',
            field=models.ManyToManyField(related_name='online_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
